esphome:
  name: m5core2
  friendly_name: M5Core2
  min_version: 2025.12.0

esp32:
  board: m5stack-core2
  framework:
    type: arduino

psram:
  mode: quad
  speed: 80MHz

logger:
  level: DEBUG
  logs:
    sensor: INFO  

api:

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "M5Core2 Fallback"
    password: !secret fallback_ap_password

captive_portal:

# TBD: Disable for production
web_server:
  port: 80

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    # TBD: set to false for production
    scan: true


i2c_device:
  id: axp_raw
  address: 0x34
  i2c_id: bus_a

external_components:
  - source:
      type: local
      path: /config/esphome/my_components/esphome-axp2101/components
    components: [ axp2101 ]
    # TBD: Remove for production
    refresh: 0s

sensor:
  - platform: axp2101
    model: M5CORE2
    address: 0x34
    id: axp_comp
    i2c_id: bus_a
    update_interval: 10s
    battery_voltage:
      name: "Battery Voltage"
      id: battery_voltage
      device_class: voltage
      unit_of_measurement: "V"
      state_class: measurement
    battery_level:
      name: "Battery Level"
      id: battery_level_id
      device_class: battery
      unit_of_measurement: "%"
      state_class: measurement
    battery_charging:
      name: "Battery Charging"
      id: battery_charging

binary_sensor:
  - platform: status
    name: "M5Core2 Status"
    entity_category: diagnostic

output:
  - platform: template
    id: backlight_out
    type: float
    write_action:
      - lambda: |-
          // state: 0.0 .. 1.0
          id(axp_comp).set_brightness(state);

light:
  - platform: monochromatic
    name: "M5Core2 Backlight"
    id: backlight_light
    icon: "mdi:brightness-6"
    output: backlight_out
    gamma_correct: 1.0
    restore_mode: RESTORE_DEFAULT_ON
    on_state:
      - component.update: lcd

# --- SPI (ekran) ---
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO38

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 24

display:
  - platform: ili9xxx
    id: lcd
    model: M5STACK
    dimensions: 320x240
    cs_pin: GPIO5
    dc_pin: GPIO15
    invert_colors: false
    update_interval: 2s
    lambda: |-
      const float batt_v = id(battery_voltage).state;
      const float batt_pct = id(battery_level_id).state;
      const bool charging = id(battery_charging).state;

      const float bri_pct = id(backlight_light).current_values.get_brightness() * 100.0f;

      it.fill(Color(0, 0, 0));

      it.printf(10, 50, id(roboto), "Brightness: %.0f%%", bri_pct);

      if (!isnan(batt_pct)) it.printf(10, 90,  id(roboto), "Battery: %.0f%%", batt_pct);
      else                  it.printf(10, 90,  id(roboto), "Battery: --%%");

      if (!isnan(batt_v))   it.printf(10, 130, id(roboto), "Voltage: %.2f V", batt_v);
      else                  it.printf(10, 130, id(roboto), "Voltage: --.- V");

      it.printf(10, 170, id(roboto), "Charging: %s", charging ? "YES" : "NO");
